<a href="https://colab.research.google.com/github/YANZHANLIN/Pytorch_exercise/blob/main/PYTORCH241007.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# COURSE1-3 TORCH BASIC

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
my_torch3 = my_torch2.reshape(-1,2)
my_torch3

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [7]:
my_torch4 = torch.arange(15)
my_torch4

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
my_torch4 = my_torch4.view(5,-1)
my_torch4

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [9]:
my_torch4 = my_torch4.reshape(5,-1)
my_torch4

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [10]:
# difference between view and reshape in pytorch?


In [11]:
# with reshape and view, they will update

In [12]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [15]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [16]:
# slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# grab a specific item
my_torch7[7]

tensor(7)

In [18]:
# grab slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [19]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [20]:
# return a column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

# COURSE4 TORCH BASIC

In [21]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [22]:
#addition shorthand
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [23]:
#addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [24]:
# subtract
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [25]:
#remainder  ?
torch.remainder(tensor_a, tensor_b)

tensor([1, 2, 3, 4])

In [26]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [27]:
#multiplication
tensor_b * tensor_a

tensor([ 5, 12, 21, 32])

In [28]:
#power of/exponents
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [29]:
#reassignment
tensor_a = tensor_a +tensor_b
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [30]:
tensor_a

tensor([11, 14, 17, 20])

In [32]:
# error!!!!
#torch.add_(tensor_a, tensor_b)

# COURSE5--BUILD BASIC NN